"use client";

import type { Metadata } from "next";
import { AnimatePresence, motion } from "framer-motion";
import { usePathname } from "next/navigation";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/styles/theme";
import { CssBaseline } from "@mui/material";
import { Outfit } from "next/font/google";
import { PromptContextProvider } from "@/context/promptContext";
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get the current route for unique animations

  return (
    <html lang="en">
      <body
        className={` antialiased`} // Default to no scroll
      >
        <PromptContextProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <AnimatePresence mode="wait">
            <motion.div
              key={pathname}
              initial={{ opacity: 0}}
              animate={{ opacity: 1}}
              transition={{
                duration: 0.5,
                ease: [0.42, 0, 0.58, 1],
              }}
              className="min-h-screen"
            >
              {children}
            </motion.div>
          </AnimatePresence>
        </ThemeProvider>
        </PromptContextProvider>
      </body>
    </html>
  );
}
